language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

install:
 - composer install --no-interaction

script:
 - composer run-script build-phar
